# TODO remove the creation of build-css-tmp branch, checkout ${{ github.head_ref }} instead
# and figure out how to make two commits without hitting fast forward errors.

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build_theme_css:
    name: Build Theme CSS
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.post_build_status.outputs.status }}
    steps:
      - name: Create build-css-temp branch
        # https://github.com/marketplace/actions/create-branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: build-css-tmp
          sha: "${{ github.event.pull_request.branch.sha }}"

      - name: Checkout build-css-temp branch
        # https://github.com/actions/checkout
        uses: actions/checkout@v3
        with:
          ref: build-css-tmp

      - name: Compile vanguard-history theme css
        # https://github.com/marketplace/actions/sass-build
        uses: gha-utilities/sass-build@v0.4.10
        with:
          source: ./wp-content/themes/vanguard-history/style.scss
          destination: ./wp-content/themes/vanguard-history/style.css

      - name: Ensure CSS has newline at EOF
        # https://github.com/marketplace/actions/newline-action
        uses: Logerfo/newline-action@0.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .github/newline.yml

      - name: Post build status
        id: post_build_status
        run: |
          echo "status=$(git status --short)"
          echo "status=$(git status --short)" >> $GITHUB_OUTPUT

      - name: Add Comment
        # https://github.com/marketplace/actions/comment-pull-request
        uses: thollander/actions-comment-pull-request@v2
        if: ${{ steps.post_build_status.outputs.status != '' }}
        with:
          message: |
            :robot: SASS changes detected - CSS has been rebuilt.
            ```
            ${{ steps.post_build_status.outputs.status }}
            ```

      - name: Commit built css
        # https://github.com/marketplace/actions/add-commit
        uses: EndBug/add-and-commit@v9
        if: ${{ steps.post_build_status.outputs.status != '' }}
        with:
          message: "Update Built CSS"
          default_author: github_actions

      - name: Merge build-css-temp branch in PR
        # https://github.com/marketplace/actions/merge-branch
        uses: devmasx/merge-branch@master
        if: ${{ steps.post_build_status.outputs.status != '' }}
        with:
          type: now
          from_branch: build-css-tmp
          target_branch: ${{ github.event.pull_request.head.ref }}
          github_token: ${{ github.token }}

      - name: Delete build-css-temp branch
        # https://github.com/marketplace/actions/delete-merged-branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{github.token}}
          branches: build-css-tmp
